import type { Metadata } from "next";
import { Geist, Geist_Mono, JetBrains_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import Navbar from "@/components/Navbar";
import BackToTop from "@/components/BackToTop";
import Footer from "@/components/Footer";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Analytics } from "@vercel/analytics/next"
import { AdSense } from "@/components/AdSense";
import AdConsentBanner from "@/components/AdConsentBanner";
import Script from "next/script";

const jetbrainsMono = JetBrains_Mono({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: 'Your Site Name',
    description: 'Your site description',
    images: [{
      url: '/og.png',  // Next.js automatically prepends your domain
      width: 1200,
      height: 630,
      alt: 'Site preview'
    }],
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={jetbrainsMono.variable} suppressHydrationWarning>
      <head>
        <meta name="5aee9cfd3e789bf778bf646a89168a1434b6d6fd" content="5aee9cfd3e789bf778bf646a89168a1434b6d6fd" />
        <meta name="referrer" content="no-referrer-when-downgrade" />
        <link rel="dns-prefetch" href="//img.gamepix.com" />
        <link rel="preconnect" href="https://img.gamepix.com" crossOrigin="" />

        {/* adsterra Popunder ads  */}
        {/* <script src="https://pl28670247.effectivegatecpm.com/5b/33/a3/5b33a3132415603db7aafc4fe32678cb.js"></script> */}

        {/* hilltopads ads script */}
        {/* <Script
          id="elderlygoal-inline-ad"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
      (function(wqo){
        var d = document,
            s = d.createElement('script'),
            l = d.scripts[d.scripts.length - 1];
        s.settings = wqo || {};
        s.src = "//elderlygoal.com/c-DW9.6Eb/2q5LljS/WaQj9/NCjecP4PMojIcVyRMaSU0c2tNHzKgXyJNtzFI/1f";
        s.async = true;
        s.referrerPolicy = 'no-referrer-when-downgrade';
        l.parentNode.insertBefore(s, l);
      })({});
    `,
          }}
        /> */}


        {/* google adsense */}
        <meta name="google-adsense-account" content="ca-pub-8288956475423358" />



      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* adsterra Popunder ads  */}
        {/* <script src="https://charlottemice.com/5b/33/a3/5b33a3132415603db7aafc4fe32678cb.js"></script> */}

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          <main id="main-content">
            {children}
          </main>
          <BackToTop />
          <Footer />
        </ThemeProvider>
        <SpeedInsights />
        <Analytics />
        <Script
          id="speedvitals-rum"
          data-rum-site-id="05035613-2bc3-4d13-83ac-9e544044a0d0"
          data-rum-spa="true"
          src="https://assets.speedvitals.com/vitals.min.js"
          strategy="afterInteractive"
        />
        <AdConsentBanner />
        <AdSense pId="8288956475423358" />


        {/* hilltopads ads script */}
        {/* <Script
          id="elderlygoal-inline-ad"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
    (function(fhe){
var d = document,
    s = d.createElement('script'),
    l = d.scripts[d.scripts.length - 1];
s.settings = fhe || {};
s.src = "\/\/villainous-end.com\/bIXCVls.dqGBlX0eYmWTca\/fe\/mN9Vu\/ZTUslikaP\/TSY\/3LOrDDMixnOeTCMJtWNqjycP4lMdzUEx5dNawJ";
s.async = true;
s.referrerPolicy = 'no-referrer-when-downgrade';
l.parentNode.insertBefore(s, l);
})({})
    `,
          }}
        /> */}


        {/* <script async data-cfasync="false" src="https://pl28670306.effectivegatecpm.com/38fffe0d1714cf5ac3cc0455e8dd63de/invoke.js"></script>
        <div id="container-38fffe0d1714cf5ac3cc0455e8dd63de"></div> */}

        {/* adsterra Social Bar */}
        {/* <script src="https://pl28670647.effectivegatecpm.com/b5/c6/d0/b5c6d0de27480c1d95e5a14cef34229a.js"></script> */}






      </body>
    </html>
  );
}
